config/routes.rb
Rails.application.routes.draw do
  resources :spaces
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/space.rb
class Space < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  before_action :set_space, only: [:show, :edit, :update, :destroy]

  # GET /spaces
  # GET /spaces.json
  def index
    # @spaces = Space.all
    @spaces = Space.paginate(:page => params[:page], :per_page => 5)
  end

  # GET /spaces/1
  # GET /spaces/1.json
  def show
  end

  # GET /spaces/new
  def new
    @space = Space.new
  end

  # GET /spaces/1/edit
  def edit
  end

  # POST /spaces
  # POST /spaces.json
  def create
    @space = Space.new(space_params)

    respond_to do |format|
      if @space.save
        format.html { redirect_to @space, notice: 'Space was successfully created.' }
        format.json { render :show, status: :created, location: @space }
      else
        format.html { render :new }
        format.json { render json: @space.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spaces/1
  # PATCH/PUT /spaces/1.json
  def update
    respond_to do |format|
      if @space.update(space_params)
        format.html { redirect_to @space, notice: 'Space was successfully updated.' }
        format.json { render :show, status: :ok, location: @space }
      else
        format.html { render :edit }
        format.json { render json: @space.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spaces/1
  # DELETE /spaces/1.json
  def destroy
    @space.destroy
    respond_to do |format|
      format.html { redirect_to spaces_url, notice: 'Space was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_space
      @space = Space.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def space_params
      params.require(:space).permit(:name, :address, :hourly_price, :daily_price, :square_footage, :capacity, :views_count, :primary_photo_css_url_small)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BusinessTravel</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/spaces/_form.html.erb
<%= form_with(model: space, local: true) do |form| %>
  <% if space.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(space.errors.count, "error") %> prohibited this space from being saved:</h2>

      <ul>
      <% space.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :space_name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :space_address %>
  </div>

  <div class="field">
    <%= form.label :hourly_price %>
    <%= form.text_field :hourly_price, id: :space_hourly_price %>
  </div>

  <div class="field">
    <%= form.label :daily_price %>
    <%= form.text_field :daily_price, id: :space_daily_price %>
  </div>

  <div class="field">
    <%= form.label :square_footage %>
    <%= form.number_field :square_footage, id: :space_square_footage %>
  </div>

  <div class="field">
    <%= form.label :capacity %>
    <%= form.number_field :capacity, id: :space_capacity %>
  </div>

  <div class="field">
    <%= form.label :views_count %>
    <%= form.number_field :views_count, id: :space_views_count %>
  </div>

  <div class="field">
    <%= form.label :primary_photo_css_url_small %>
    <%= form.text_area :primary_photo_css_url_small, id: :space_primary_photo_css_url_small %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/spaces/edit.html.erb
<h1>Editing Space</h1>

<%= render 'form', space: @space %>

<%= link_to 'Show', @space %> |
<%= link_to 'Back', spaces_path %>

app/views/spaces/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Spaces</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Hourly price</th>
      <th>Daily price</th>
      <th>Square footage</th>
      <th>Capacity</th>
      <th>Views count</th>
      <th>Primary photo css url small</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @spaces.each do |space| %>
      <tr>
        <td><%= space.name %></td>
        <td><%= space.address %></td>
        <td><%= space.hourly_price %></td>
        <td><%= space.daily_price %></td>
        <td><%= space.square_footage %></td>
        <td><%= space.capacity %></td>
        <td><%= space.views_count %></td>
        <td><%= space.primary_photo_css_url_small %></td>
        <td><%= link_to 'Show', space %></td>
        <td><%= link_to 'Edit', edit_space_path(space) %></td>
        <td><%= link_to 'Destroy', space, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Space', new_space_path %>

app/views/spaces/new.html.erb
<h1>New Space</h1>

<%= render 'form', space: @space %>

<%= link_to 'Back', spaces_path %>

app/views/spaces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @space.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @space.address %>
</p>

<p>
  <strong>Hourly price:</strong>
  <%= @space.hourly_price %>
</p>

<p>
  <strong>Daily price:</strong>
  <%= @space.daily_price %>
</p>

<p>
  <strong>Square footage:</strong>
  <%= @space.square_footage %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @space.capacity %>
</p>

<p>
  <strong>Views count:</strong>
  <%= @space.views_count %>
</p>

<p>
  <strong>Primary photo css url small:</strong>
  <%= @space.primary_photo_css_url_small %>
</p>

<% will_paginate @spaces %>

<%= link_to 'Edit', edit_space_path(@space) %> |
<%= link_to 'Back', spaces_path %>